### ISSUE TITLE
Can't compile for m5stack atom lite bt proxy

### ISSUE THREAD

**Issue by dixonbg** [jesserockz/wizmote-esphome#13]
Hi there,

I've recently bought a Wizmote, thinking I can link it with the Wiz integration.
Now that I know it broadcast some ESPNOW packets, I thought that my tiny Bluetooth proxy can capture these too.
Unfortunately, my understanding of ESPHome is not enough to resolve the errors during compilation:

```
Compiling /data/atom-bluetooth-proxy-9fac9c/.pioenvs/atom-bluetooth-proxy-9fac9c/src/main.o
Linking /data/atom-bluetooth-proxy-9fac9c/.pioenvs/atom-bluetooth-proxy-9fac9c/firmware.elf
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/atom-bluetooth-proxy-9fac9c/.pioenvs/atom-bluetooth-proxy-9fac9c/src/main.o:(.literal._Z5setupv+0xc4): undefined reference to `vtable for esphome::wizmote::WizMoteListener'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/atom-bluetooth-proxy-9fac9c/.pioenvs/atom-bluetooth-proxy-9fac9c/src/main.o:(.literal._Z5setupv+0x188): undefined reference to `esphome::esp_now::ESPNowComponent::ESPNowComponent()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/atom-bluetooth-proxy-9fac9c/.pioenvs/atom-bluetooth-proxy-9fac9c/src/main.o: in function `setup()':
/config/esphome/.esphome/build/atom-bluetooth-proxy-9fac9c/src/main.cpp:218: undefined reference to `esphome::esp_now::ESPNowComponent::ESPNowComponent()'
collect2: error: ld returned 1 exit status
*** [/data/atom-bluetooth-proxy-9fac9c/.pioenvs/atom-bluetooth-proxy-9fac9c/firmware.elf] Error 1
========================= [FAILED] Took 23.35 seconds =========================
```

I've just pasted the yaml at the end... but it doesn't work

```yaml
substitutions:
  name: atom-bluetooth-proxy-9fac9c
  friendly_name: Bluetooth Proxy 9fac9c
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/m5stack-atom-lite.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: =
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
external_components:
  - source: github://jesserockz/wizmote-esphome
    components:
      - esp_now
      - wizmote
esp_now:
wizmote:
  on_button:
    if:
      condition:
        lambda: return data.button >= 16 && data.button <= 19;
      then:
        - homeassistant.event:
            event: esphome.wizmote_choose
            data:
              mac: !lambda 'return format_hex(data.bssid, 6);'
              button: !lambda 'return data.button - 15;'
              sequence: !lambda 'return data.sequence;'
      else:
        - homeassistant.event:
            event: esphome.wizmote_action
            data:
              mac: !lambda 'return format_hex(data.bssid, 6);'
              button: !lambda 'return data.button;'
              sequence: !lambda 'return data.sequence;'
```

Thank you for your efforts
