### ISSUE TITLE
Code not optimised for multiple remotes. 

### ISSUE THREAD

**Issue by TheAussieEngineer** [jesserockz/wizmote-esphome#14]
wizmote.cpp having the following:
if (wizmote.sequence <= this->last_sequence_)
    return;

prevents the effective use of multiple remotes. In short this bit of code will only allow the remote with the highest sequence to record events in HA. I recommend changing to the following:
if (wizmote.sequence == this->last_sequence_)
    return;

This code will prevent rapid multi call of the events whilst also allowing multiple remotes to be used.

**Comment by krakowski** [comment]
Someone had the same suggestion in the past here: https://github.com/jesserockz/wizmote-esphome/issues/4#issuecomment-1186115952

Looks like it never made it into the code, though.

**Comment by TheAussieEngineer** [comment]
> Someone had the same suggestion in the past here: [#4 (comment)](https://github.com/jesserockz/wizmote-esphome/issues/4#issuecomment-1186115952)
> 
> Looks like it never made it into the code, though.

seen and good pickup. For anyone who it trying to used multiple remotes you can edit the file through the HA file editor (after the first time that the ESP has been updated). For me the file was at: /config/esphome/.esphome/external_components/343b74af/components/wizmote/wizmote.cpp

**Comment by jonofmac** [comment]
Looks like today Jesse merged my PR (#9 ) which fixes this and supports up to 15 remotes simultaneously (this limit is easily changed by modifying a define).

**Comment by jrspowers** [comment]
> Het lijkt erop dat Jesse vandaag mijn PR ([# 9](https://github.com/jesserockz/wizmote-esphome/pull/9) ) heeft samengevoegd, die dit oplost en tot 15 afstandsbedieningen tegelijkertijd ondersteunt (deze limiet kan eenvoudig worden gewijzigd door een definitie te wijzigen).

Hey, I have a question. I can't get the wizmote to work. I have an ESP32 with this code:

```yaml
esphome:
  name: wizmote
  friendly_name: wizmote

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "secrid"

ota:
  password: "secrid"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wizmote Fallback Hotspot"
    password: "secrid"

captive_portal:
    
external_components:
  - source: github://jesserockz/wizmote-esphome
    components:
      - esp_now
      - wizmote

esp_now:

wizmote:
  on_button:
    if:
      condition:
        lambda: return data.button >= 16 && data.button <= 19;
      then:
        - homeassistant.event:
            event: esphome.wizmote_choose
            data:
              mac: !lambda 'return format_hex(data.bssid, 6);'
              button: !lambda 'return data.button - 15;'
              sequence: !lambda 'return data.sequence;'
      else:
        - homeassistant.event:
            event: esphome.wizmote_action
            data:
              mac: !lambda 'return format_hex(data.bssid, 6);'
              button: !lambda 'return data.button;'
              sequence: !lambda 'return data.sequence;'
```

And I'm using the blueprint, but when I click on button 1, the lamp doesn't turn on. I've entered the correct MAC address, so what's wrong?
