### ISSUE TITLE
Wiz Smart Button

### ISSUE THREAD

**Issue by micw** [jesserockz/wizmote-esphome#18]
Not an issue. Just wanted you to know that "Wiz Smart Button" (https://www.wizconnected.com/en-gb/p/accessory-smart-button/8719514554795) also works. Button IDs are

100: on
101: off
102: brightness plus (long-press to "on")
102: brightness minus (long-press to "off")

**Comment by micw** [comment]
You use it in your config, see example:

```
      condition:
        lambda: return data.button >= 16 && data.button <= 19;
```

Buttons on this remote are 100...102.

**Comment by ImaZen88** [comment]
Thanks a lot, but I still have no events in event log.

```
esphome:
  name: wiz-bridge
  friendly_name: wiz-bridge

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "1x6vW9uDccJbWrdPja9P0ElthJ7Exd4bc5vYzdhMNHY="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wiz-Bridge Fallback Hotspot"


captive_portal:


external_components:
  - source: github://jesserockz/wizmote-esphome
    components:
      - esp_now
      - wizmote

esp_now:

wizmote:
  on_button:
    if:
      condition:
        lambda: return data.button >= 100 && data.button <= 102;
      then:
        - homeassistant.event:
            event: esphome.wizmote_choose
            data:
              mac: !lambda 'return format_hex(data.bssid, 6);'
              button: !lambda 'return data.button;'
              sequence: !lambda 'return data.sequence;'
      else:
        - homeassistant.event:
            event: esphome.wizmote_action
            data:
              mac: !lambda 'return format_hex(data.bssid, 6);'
              button: !lambda 'return data.button;'
              sequence: !lambda 'return data.sequence;'
```

I am grateful for such a fast response, but I am really lost here, did you encounter this problem too and if, how did you solve it?
Thanks

**Comment by ImaZen88** [comment]
It's not working even if I remove the condition
```
esphome:
  name: wiz-bridge
  friendly_name: wiz-bridge

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "1x6vW9uDccJbWrdPja9P0ElthJ7Exd4bc5vYzdhMNHY="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wiz-Bridge Fallback Hotspot"


captive_portal:


external_components:
  - source: github://jesserockz/wizmote-esphome
    components:
      - esp_now
      - wizmote

esp_now:

wizmote:
  on_button:
      - homeassistant.event:
          event: esphome.wizmote_test
          data:
            mac: !lambda 'return format_hex(data.bssid, 6);'
            button: !lambda 'return data.button - 99;'
            sequence: !lambda 'return data.sequence;'    

```
