### ISSUE TITLE
No events on the bus

### ISSUE THREAD

**Issue by devinalonzo** [jesserockz/wizmote-esphome#19]
For a few months I have not been getting events from the esp to the home assistant event bus. In the esplogger I can see the button presses but not under the "developer tools - events - listen to events". I tried flashing all the default code to the esp. Not sure if it was an update that broke it or if I did something or what. Any ideas?

**Comment by traxeon** [comment]
I am able to see events on the bus.  Listen to events - use one of the two below and click on start listening.   Or use * > "start listening" and they should appear.
event_type: esphome.wizmote_action
event_type: esphome.wizmote_choose

When setting up the firmware in ESPhome, make sure to APPEND the code from "ESPHome configuration snippet" to the default code generated for ESPhome.  Then flash the ESP32.

**Comment by traxeon** [comment]
I wont lie.  Using this integration was difficult to figure out, but I'm super grateful someone built it.   If you want to use the automation, here is a simple YAML that will toggle a light.
```
alias: Test wizmote events
description: "Use for turning on and off device only"
trigger:
  - platform: event
    event_type: esphome.wizmote_action
    event_data:
      device_id: 120852eaa13a46c8a25d49606dc97eb0
      mac: 444f8ebea8f7
      button: "1"
    id: wizmote_button_on
  - platform: event
    event_type: esphome.wizmote_action
    event_data:
      device_id: 120852eaa13a46c8a25d49606dc97eb0
      mac: 444f8ebea8f7
      button: "2"
    id: wizmote_button_off
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - wizmote_button_on
        sequence:
          - type: turn_on
            device_id: bb24fc41acc6a68faeed97a52a826a34
            entity_id: 00522b0237c1928cf5fcff97fa245926
            domain: switch
      - conditions:
          - condition: trigger
            id:
              - wizmote_button_off
        sequence:
          - type: turn_off
            device_id: bb24fc41acc6a68faeed97a52a826a34
            entity_id: 00522b0237c1928cf5fcff97fa245926
            domain: switch
mode: single
```

**Comment by traxeon** [comment]
i'm feeling particularly sharing today.  if you want to dump the events into MQTT... 
```
alias: Test wizmote to mqtt
description: ""
trigger:
  - platform: event
    event_type: esphome.wizmote_action
    event_data:
      mac: <your_mac_without_punctuation>
    id: wizmote_action
  - platform: event
    event_type: esphome.wizmote_choose
    event_data:
      mac: <your_mac_without_punctuation>
    id: wizmote_choose
condition:
  - condition: trigger
    id:
      - wizmote_action
      - wizmote_choose
action:
  - service: mqtt.publish
    data:
      qos: "1"
      payload_template: "{{ trigger.event }}"
      topic: wizmote/event
mode: single
```
