### ISSUE TITLE
wizmote doesn't work when not connected to an ap

### ISSUE THREAD

**Issue by docteurzoidberg** [jesserockz/wizmote-esphome#33]
Hi Jesse ans thanks for this component !

Just received my wizmote, and it seems to not work when the esp isn't connected to an AP.

It then works as soon as i put a valid AP + credentials and the esp connects to it.

I wanted to know if espnow / wizmote can work without being connected (i plan to use it on a standalone esp in my RV qhich don't have wifi router enabled all the time) 

Thanks !

sample config for reference:  

 ```yaml

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

substitutions:
  log_level: INFO
    
esphome:
  name: "esphome-test-wizmote"
  friendly_name: Test wizmote
  min_version: 2024.12.4
  name_add_mac_suffix: false

external_components:
  - source: github://jesserockz/wizmote-esphome
    components:
      - esp_now
      - wizmote

wifi:
  reboot_timeout: 0s
  #power_save_mode: none
  networks:
    - ssid: !secret wifi_home_ssid
      password: !secret wifi_home_password
    - ssid: !secret wifi_j7_ssid
      password: !secret wifi_j7_password
  #on_connect:

esp_now:

logger:
  level: $log_level

wizmote:
  on_button:
      - logger.log:
          level: INFO
          format: "Wizmote data received ! bssid: %s, button: %d, sequence: %f"
          args: [ 'format_hex(data.bssid, 6)', 'data.button', 'data.sequence' ]

 ```
