### ISSUE TITLE
espnow compilation fail when using esp-idf

### ISSUE THREAD

**Issue by docteurzoidberg** [jesserockz/wizmote-esphome#34]
same as previous one, thanks again for your work !

i was able to compile your components on arduino framework but not esp-idf one

ESPHome 2025.2.0

Logs:
 `
src/esphome/components/esp_now/esp_now_component.cpp: In member function 'virtual void esphome::esp_now::ESPNowComponent::setup()':
src/esphome/components/esp_now/esp_now_component.cpp:32:33: error: invalid conversion from 'void (*)(const uint8_t*, const uint8_t*, int)' {aka 'void (*)(const unsigned char*, const unsigned char*, int)'} to 'esp_now_recv_cb_t' {aka 'void (*)(const esp_now_recv_info*, const unsigned char*, int)'} [-fpermissive]
   32 |   err = esp_now_register_recv_cb(ESPNowComponent::on_data_received);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                 |
      |                                 void (*)(const uint8_t*, const uint8_t*, int) {aka void (*)(const unsigned char*, const unsigned char*, int)}
In file included from src/esphome/components/esp_now/esp_now_component.cpp:4:
/home/drzoid/.platformio/packages/framework-espidf/components/esp_wifi/include/esp_now.h:157:54: note:   initializing argument 1 of 'esp_err_t esp_now_register_recv_cb(esp_now_recv_cb_t)'
  157 | esp_err_t esp_now_register_recv_cb(esp_now_recv_cb_t cb);
      |                                    ~~~~~~~~~~~~~~~~~~^~
Compiling .pioenvs/esphome-test-wizmote/src/esphome/components/logger/logger_esp32.cpp.o
*** [.pioenvs/esphome-test-wizmote/src/esphome/components/esp_now/esp_now_component.cpp.o] Error 1
`

Sample config:

```yaml
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

substitutions:
  log_level: INFO
    
esphome:
  name: "esphome-test-wizmote"
  friendly_name: Test wizmote
  name_add_mac_suffix: false

external_components:
  - source: github://jesserockz/wizmote-esphome
    components:
      - esp_now
      - wizmote

wifi:
  reboot_timeout: 0s
  #power_save_mode: none
  networks:
    - ssid: !secret wifi_home_ssid
      password: !secret wifi_home_password
    - ssid: !secret wifi_j7_ssid
      password: !secret wifi_j7_password

esp_now:

logger:
  level: $log_level

wizmote:
  on_button:
      - logger.log:
          level: INFO
          format: "Wizmote data received ! bssid: %s, button: %d, sequence: %f"
          args: [ 'format_hex(data.bssid, 6)', 'data.button', 'data.sequence' ]

```
